/**
 * Type declarations for the llguidance WASM module.
 * These types describe the interface generated by wasm-bindgen.
 */

declare module 'llguidance-wasm' {
  /**
   * Initialize the WASM module
   */
  export default function init(): Promise<void>;

  /**
   * The main parser class exposed by WASM
   */
  export class LLGuidanceParser {
    /**
     * Create a new parser instance
     * @param grammar_json JSON string containing the grammar definition
     * @param tokenizer_json JSON string containing the tokenizer configuration
     */
    constructor(grammar_json: string, tokenizer_json: string);

    /**
     * Check if a specific token is allowed at the current position
     */
    is_token_allowed(token_id: number): boolean;

    /**
     * Get the full token mask for the current position
     * Returns a Uint8Array where 1 = allowed, 0 = banned
     */
    get_token_mask(): Uint8Array;

    /**
     * Advance the parser state after a token has been selected
     */
    advance(token_id: number): void;

    /**
     * Check if the current state represents a valid complete parse
     */
    is_complete(): boolean;

    /**
     * Reset the parser to its initial state
     */
    reset(): void;

    /**
     * Get the vocabulary size
     */
    vocab_size(): number;

    /**
     * Check if the parser is in an error state
     */
    is_error(): boolean;

    /**
     * Get the current error message, if any
     */
    get_error(): string | null;
  }
}

